config/routes.rb
Rails.application.routes.draw do
  resources :tax_rates
  get 'payslip/index'
  resources :employees
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  get '/payslip',          to: 'payslip#index',           as: :payslips
  post '/payslip/multiple', to: 'payslip#show_multiple',  as: :payslips_multiple
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/payslip.rb
class Payslip

  include ActiveModel::Model
  attr_accessor :employee, :pay_period_start_date, :pay_period_end_date
  attr_reader :calculation


  def initialize(attributes={})
    super
    @calculation = PayslipCalculator.new(
        annual_salary: @employee.annual_salary,
        super_rate: @employee.super_rate,
        pay_period_start_date: @pay_period_start_date,
        pay_period_end_date: @pay_period_end_date,
        annual_tax: TaxRange.annual_tax(@employee.annual_salary)
    ) if self.valid?
  end

  validates :employee, :pay_period_start_date, :pay_period_end_date, presence: true
  validate :dates_are_in_the_same_month?


  def name
    @employee.full_name
  end

  def pay_period
    "#{@pay_period_start_date} - #{@pay_period_end_date}"
  end

  def gross_income
    @calculation.gross_income
  end

  def income_tax
    @calculation.income_tax
  end

  def net_income
    @calculation.net_income
  end

  def super_amount
    @calculation.super_amount
  end

  private

  def dates_are_in_the_same_month?
    if @pay_period_start_date.to_d == @pay_period_end_date.to_d
      true
    else
      errors.add(:pay_period_end_date, 'must be in the same month as start date')
      false
    end
  end

end

app/models/payslip_calculator.rb
class PayslipCalculator

  include ActiveModel::Model
  attr_accessor :annual_salary, :super_rate, :pay_period_start_date, :pay_period_end_date, :annual_tax
  attr_reader :start_date, :end_date, :incomplete_month

  def initialize(attributes={})
    super
    @start_date       = @pay_period_start_date.to_d
    @end_date         = @pay_period_end_date.to_d
    @incomplete_month = incomplete_month_calculation
  end

  def gross_income
    ((@annual_salary.to_f / 12) * @incomplete_month).round(0).to_i
  end

  def income_tax
    (((@annual_tax.to_f / 12) * @incomplete_month).round(0)).to_i
  end

  def net_income
    (self.gross_income - self.income_tax).to_i
  end

  def super_amount
    (self.gross_income * @super_rate).round(0).to_i
  end

  private

  def incomplete_month_calculation
    if first_date_of_month? && last_date_of_month?
      1
    else
      fraction_part_of_month
    end
  end

  def first_date_of_month?
    @start_date == @start_date.at_beginning_of_month
  end

  def last_date_of_month?
    @end_date == @end_date.at_end_of_month
  end

  def fraction_part_of_month
    work_days_in_this_month = @start_date.at_beginning_of_month.business_days_until(@start_date.at_end_of_month)
    worked_days = @start_date.business_days_until(@end_date)
    worked_days.to_f / work_days_in_this_month.to_f
  end
end

app/models/tax_rates.rb
# == Schema Information
#
# Table name: tax_rates
#
#  id                   :integer          not null, primary key
#  min_income           :integer
#  max_income           :integer
#  rates                 :decimal(, )
#  tax_from_lower_range :integer
#

class TaxRates < ActiveRecord::Base

  class << self

    def valid_tax_range(annual_salary)
      if annual_salary > 0
        TaxRange.where('min_income <= ? AND ? <= max_income', annual_salary, annual_salary).first
      else
        nil
      end
    end

    def annual_tax(annual_salary)
      if annual_salary > 0
        vtr = self.valid_tax_range(annual_salary)
        (vtr.tax_from_lower_range + ((annual_salary - (vtr.min_income-1))*vtr.rates)).round(3)
      else
        nil
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :staff_id, :email, :phone, :annual_salary, :rate, :create_date, :update_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payslip_controller.rb
class PayslipController < ApplicationController
  before_action :set_form_params
  before_action :set_params,        only: [:show_multiple]

  def index
    @tax_range_empty ||= TaxRates.all.empty?
    flash.now[:error] = 'Please run rake db:seed to setup Tax Range model. Payslip generator cannot work without valid tax ranges.'if @tax_range_empty
  end

  def show_multiple
    respond_to do |format|
      if payslip_collection
        format.js { render 'show_multiple' }
        format.csv
      else
        flash[:error] = @errors.full_messages
        format.js { render 'show_multiple_error' }
      end
    end
  end

  def set_form_params
    @employees_for_select ||= Employee.all
  end

  def payslip_collection
     @payslips = []; @errors = ''
     @employees.each do |employee|
       payslip = Payslip.new(employee: employee, pay_period_start_date: @pay_period_start_date, pay_period_end_date: @pay_period_end_date )
       if payslip.errors.any?
         @errors = payslip.errors
       else
         @payslips << payslip.all
       end
     end
     @errors.empty?
  end

  def set_params
    @employees  = Employee.find(payslip_params[:employee_id])     if payslip_params[:employee_id]
    @pay_period_start_date = payslip_params[:payslip_start_date]  if payslip_params[:payslip_start_date]
    @pay_period_end_date   = payslip_params[:payslip_end_date]    if payslip_params[:payslip_end_date]
    @params_for_csv = {employee_id: @employees.map(&:id), payslip_end_date: @pay_period_end_date, payslip_start_date: @pay_period_start_date}
  end

  def payslip_params
    params[:payslips]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payslip_helper.rb
module PayslipHelper
end

app/helpers/tax_rates_helper.rb
module TaxRatesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :staff_id %>
    <%= form.text_field :staff_id, class:"form-control", placeholder:"Staff Id" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="field form-group">
    <%= form.label :annual_salary %>
    <%= form.text_field :annual_salary, class:"form-control", placeholder:"Annual Salary (RM)" %>
  </div>

  <div class="field form-group">
    <%= form.label :rate %>
    <%= form.text_field :rate, class:"form-control", placeholder:"Rates (%)" %>
  </div>

  <div class="field form-group">
    <%= form.label :create_date %>
    <%= form.datetime_select :create_date, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :update_date %>
    <%= form.datetime_select :update_date, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Update Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee, class:"btn btn-primary mt-2 mb-2" %>
<%= link_to '<< Back', employees_path, class:"btn btn-secondary mt-2 mb-2" %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<%= link_to 'Add Employee', new_employee_path, class:"btn btn-primary mb-3" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Staff</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Annual salary</th>
      <th>Rate</th>
      <th>Create date</th>
      <th>Update date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.staff_id %></td>
        <td><%= employee.email %></td>
        <td><%= employee.phone %></td>
        <td>RM <%= employee.annual_salary %></td>
        <td><%= employee.rate %> %</td>
        <td><%= employee.create_date %></td>
        <td><%= employee.update_date %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<h1>Add New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to '<< Back', employees_path, class:"small btn btn-secondary mt-2 mb-2" %>

app/views/employees/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">[<%= @employee.staff_id %>] <%= @employee.first_name %> <%= @employee.last_name %></h1>
  <p><%= @employee.email %> | <%= @employee.phone %> | RM <%= @employee.annual_salary %> | <%= @employee.rate %> % | <%= @employee.create_date %></p>
</div>

<p class="lead">
    <%= link_to 'Edit', edit_employee_path(@employee), class:"btn btn-primary" %>
<%= link_to '<< Back', employees_path, class:"btn btn-secondary" %>
  </p>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <i class="fa fa-file-invoice"></i><%= link_to 'Payslip', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Employees", employees_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Payslips", payslip_index_path, class:"nav-link" %>
      </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
  <h1>About</h1>
  <p>Fave Ruby Technical Interview</p>
  <ul> 
    <li>to create a ruby function generate_monthly_payslip to compute a monthly payslip of an individual based on his annual salary with 2 decimal places with unit tests.</li>
    <li>Create a POST REST API request to expose your function. Request parameters should include employee_name and annual_salary. The response body should return JSON format. Add unit tests where you think its relevant.</li>
    <li>When compute monthly salary POST API is invoked, Then write the following information in a database of your choice, you can use any local or cloud database</li>
    <li>Create a GET API to list out all information from Requirement 3 on JSON Format</li>
    <li>[Extra] You can implement any feature related to the APIs you just created Some ideas:<br/>
       - Build a Simple UI Form to enter transactions<br/>
       - Generate a CSV<br/>
       - Add a Github Action to automate running the unit test<br/>
       - Hook a free CI<br/>
       - Deploy to Heroku I'll be more impressed if you do something else not listed on this list For this section you can invent your own requirment</li>
  </ul>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Payslip Application</h1>
  <p>Payslip application is mainly for generate income tax and generate payslips.</p>
  <%= image_tag ("background-finance.jpeg"), class: "img-responsive h-100 w-75" %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Payslip App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/payslip/_list.html.erb
<h3 class="mt-5">Employee Payslip Details</h3>

<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Staff</th>
      <th>Pay Period</th>
      <th>Gross Income</th>
      <th>Income Tax</th>
      <th>Net Income</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
        <% if @payslips %>
        <tr>
          <td><%= payslips.first_name %></td>
          <td><%= payslips.last_name %></td>
          <td><%= payslips.staff_id %></td>
          <td><%= payslips.email %></td>
          <td><%= payslips.phone %></td>
          <td>RM <%= payslips.annual_salary %></td>
          <td><%= payslips.rate %> %</td>
          <td><%= payslips.create_date %></td>
          <td><%= payslips.update_date %></td>
          <td><%= link_to 'Show', employee %></td>
        </tr>
        <% end %>
  </tbody>
</table>

app/views/payslip/index.html.erb
<%= form_for :payslips, url: payslips_multiple_path,  method: :post, remote: :true, html: {class: 'form-horizontal'} do |form| %>
	<h1>Generate Payslip</h1>

<div class="form-group">
  <label class="mt-2">Please Select Employee Name</label>
	<%= form.select :employee_id, options_from_collection_for_select(@employees_for_select, :id, :first_name), {include_blank: false, include_hidden: false}, multiple: true, size: 5, class: 'form-control', required: true %>
</div>
<div class="form-group">
  <label>Start Date</label>
  <%= form.datetime_select :pay_period_start_date, class:"form-control" %>
</div>
<div class="form-group">
  <label>End Date</label>
  <%= form.datetime_select :pay_period_end_date, class:"form-control" %>
</div>
<div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>

<%= render 'list', payslips: @payslips, class:"mt-5" %>

<% end %>

app/views/payslip/show_multiple.csv.erb
name,pay_period,gross_income,income_tax,net_income,super
<%= CSV.generate do |csv|
  @payslips.each do |ps|
    csv << [ps.name,
            ps.pay_period,
            ps.gross_income,
            ps.income_tax,
            ps.net_income,
            ps.super_amount
            ]
  end
end.html_safe %>

app/views/payslip/show_multiple.js.erb
$('#payslip_list').html("<%=escape_javascript(render 'payslips/list')%>");

app/views/payslip/show_multiple_error.js.erb
window.location.replace("<%="#{payslips_url}"%>");